LOAD DATA INFILE 'Consolidated_Report.csv' INTO TABLE GENERAL_ELECTION_RESULTS
  FIELDS TERMINATED BY ','
  LINES TERMINATED BY '\n';

SELECT 
    COUNT(*) AS NO_OF_CANDIDATES, PARTY
FROM
    loksabha2014.GENERAL_ELECTION_RESULTS
GROUP BY PARTY
ORDER BY NO_OF_CANDIDATES DESC;

SELECT 
    COUNT(CANDIDATE) AS NO_OF_CONSTITUENCIES, CANDIDATE, PARTY
FROM
    loksabha2014.GENERAL_ELECTION_RESULTS
WHERE
    PARTY NOT LIKE 'INDEPENDENT'
GROUP BY PARTY , CANDIDATE
ORDER BY NO_OF_CONSTITUENCIES DESC;

SELECT 
    CANDIDATE, PARTY, CONSTITUENCY, VOTES
FROM
    loksabha2014.GENERAL_ELECTION_RESULTS
ORDER BY VOTES DESC;


SELECT 
    PARTY_VOTE_DETAILS.PARTY AS PARTY,
    PARTY_VOTE_DETAILS.PARTY_VOTES AS PARTY_VOTES,
    TOTAL_VOTE_DETAILS.TOTAL_VOTES AS TOTAL_VOTES,
    (PARTY_VOTE_DETAILS.PARTY_VOTES / TOTAL_VOTE_DETAILS.TOTAL_VOTES) AS VOTE_SHARE
FROM
    (SELECT 
        PARTY, SUM(VOTES) AS PARTY_VOTES
    FROM
        loksabha2014.GENERAL_ELECTION_RESULTS
    GROUP BY PARTY) AS PARTY_VOTE_DETAILS,
    (SELECT 
        SUM(VOTES) AS TOTAL_VOTES
    FROM
        loksabha2014.GENERAL_ELECTION_RESULTS) AS TOTAL_VOTE_DETAILS
ORDER BY VOTE_SHARE DESC;

SELECT 
    ger.CANDIDATE,
    ger.PARTY,
    ger.CONSTITUENCY,
    ger.VOTES,
    VOTE_DETAILS.TOTAL_VOTES,
    (ger.VOTES / VOTE_DETAILS.TOTAL_VOTES) AS VOTE_SHARE
FROM
    (SELECT 
        CONSTITUENCY, SUM(VOTES) AS TOTAL_VOTES
    FROM
        loksabha2014.GENERAL_ELECTION_RESULTS
    GROUP BY CONSTITUENCY) AS VOTE_DETAILS
        JOIN
    GENERAL_ELECTION_RESULTS ger ON VOTE_DETAILS.CONSTITUENCY = ger.CONSTITUENCY
ORDER BY VOTE_SHARE DESC;

SELECT 
    COUNT(DEPOSIT_LOSERS.PARTY) AS NO_OF_CANDIDATES_WITH_LESS_THAN_ONE_SIXTH_VOTES,
    DEPOSIT_LOSERS.PARTY
FROM
    (SELECT 
        ger.CANDIDATE,
            ger.PARTY,
            ger.CONSTITUENCY,
            ger.VOTES,
            VOTE_DETAILS.TOTAL_VOTES,
            (ger.VOTES / VOTE_DETAILS.TOTAL_VOTES) AS VOTE_SHARE
    FROM
        (SELECT 
        CONSTITUENCY, SUM(VOTES) AS TOTAL_VOTES
    FROM
        loksabha2014.GENERAL_ELECTION_RESULTS
    GROUP BY CONSTITUENCY) AS VOTE_DETAILS
    JOIN GENERAL_ELECTION_RESULTS ger ON VOTE_DETAILS.CONSTITUENCY = ger.CONSTITUENCY) DEPOSIT_LOSERS
WHERE
    VOTE_SHARE < (1 / 6)
GROUP BY DEPOSIT_LOSERS.PARTY
ORDER BY NO_OF_CANDIDATES_WITH_LESS_THAN_ONE_SIXTH_VOTES DESC;


SELECT 
	WINNER_CONSTITUENCY AS CONSTITUENCY,
    WINNER_CANDIDATE,
    WINNER_PARTY,	
    WINNER_VOTES,
    RUNNER_UP_CANDIDATE,
    RUNNER_UP_PARTY,
    MAX(CAND.RUNNER_UP_VOTES) AS RUNNER_UP_VOTES,
	(WINNER_VOTES - RUNNER_UP_VOTES) AS DIFFERENCE_IN_VOTES
FROM
    (SELECT 
        GER.CANDIDATE AS RUNNER_UP_CANDIDATE,
            GER.PARTY AS RUNNER_UP_PARTY,
            GER.CONSTITUENCY AS RUNNER_UP_CONSTITUENCY,
            GER.VOTES AS RUNNER_UP_VOTES,
            WINNER.CANDIDATE AS WINNER_CANDIDATE,
            WINNER.PARTY AS WINNER_PARTY,
            WINNER.CONSTITUENCY AS WINNER_CONSTITUENCY,
            WINNER.WINNER_VOTES AS WINNER_VOTES
    FROM
        GENERAL_ELECTION_RESULTS GER
    JOIN (SELECT 
        CANDIDATE, PARTY, CONSTITUENCY, MAX(VOTES) AS WINNER_VOTES
    FROM
        GENERAL_ELECTION_RESULTS
    GROUP BY CONSTITUENCY) AS WINNER ON GER.CONSTITUENCY = WINNER.CONSTITUENCY
    WHERE
        GER.VOTES < WINNER.WINNER_VOTES
    ORDER BY GER.VOTES DESC) CAND
GROUP BY CAND.RUNNER_UP_CONSTITUENCY
ORDER BY DIFFERENCE_IN_VOTES DESC;
